In [5]:
import numpy as np

In [6]:
arr1 = np.array([12,23,45,67,89])

In [7]:
print(arr1)

[12 23 45 67 89]


In [8]:
arr1

array([12, 23, 45, 67, 89])

In [9]:
arr2 = np.array([23,34,54,12.34,'Aditya'])

In [10]:
arr2

array(['23', '34', '54', '12.34', 'Aditya'], dtype='<U32')

In [13]:
%%timeit
arr2 = np.array([23,34,54,12.34,'Aditya'])

1.44 µs ± 53.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [14]:
arr1.dtype

dtype('int64')

In [15]:
arr2.dtype

dtype('<U32')

In [16]:
arr2.shape

(5,)

In [17]:
arr1.ndim

1

In [19]:
arr1

array([12, 23, 45, 67, 89])

In [18]:
arr1 + 10

array([22, 33, 55, 77, 99])

In [20]:
arr1[1]

23

In [21]:
# linear equation

x = np.array([23,67,34,21,89])

In [22]:
new1 = x + 3.4 + 12
new1

array([ 38.4,  82.4,  49.4,  36.4, 104.4])

In [23]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(5,25)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [27]:
np.arange(-5, 5, 0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [31]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
arr2d.ndim

2

In [34]:
type(arr2d)

numpy.ndarray

In [39]:
arr2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
arr2d.size

12

In [42]:
arr2d.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
arr2d.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [46]:
arr2d.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [47]:
arr2d.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [50]:
arr2d.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [60]:
arr4d = np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])

In [61]:
arr4d

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [62]:
arr4d.ndim

4

In [63]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [64]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
arr2d[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [66]:
arr2d[1,1]

5

In [72]:
arr = np.array([2,4,np

In [73]:
np.unique(arr)

array([-1,  2,  4,  5,  7,  8])

In [74]:
np.mean(arr)

3.7777777777777777

In [75]:
np.max(arr)

8

In [76]:
np.abs(arr)

array([2, 4, 5, 7, 2, 2, 8, 5, 1])